### ISSUE TITLE
Not able to run the Android app version ^5.0.1+1

### ISSUE THREAD

**Issue by signshah** [Baseflow/flutter-permission-handler#415]
## 🔙 Regression

I am not able to run the app in the Android emulator and it gives the following error:

*** What went wrong:**
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Old (and correct) behavior
Since yesterday, I was able to run the app without any issue. Today I upgraded my dependency to the latest one which is **5.0.1+1**. Since then it is not working even i reverted back to the previous version it is not working.

### Current behavior
As and when I click on Run button it gives the error.

**Version:** 1.x
permission_handler: ^5.0.1+1

**Platform:** 
- [ ] :robot: Android

**Full Error**:
          
          Note: /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.7.0+1/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
          Note: Recompile with -Xlint:deprecation for details.
          Note: Some input files use or override a deprecated API.
          Note: Recompile with -Xlint:deprecation for details.
          Note: Some input files use unchecked or unsafe operations.
          Note: Recompile with -Xlint:unchecked for details.
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:358: error: cannot find symbol
          if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
          ^
          symbol:   variable Q
          location: class VERSION_CODES
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:33: error: cannot find symbol
          case Manifest.permission.ACCESS_BACKGROUND_LOCATION:
          ^
          symbol:   variable ACCESS_BACKGROUND_LOCATION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:46: error: cannot find symbol
          case Manifest.permission.BIND_CALL_REDIRECTION_SERVICE:
          ^
          symbol:   variable BIND_CALL_REDIRECTION_SERVICE
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:59: error: cannot find symbol
          case Manifest.permission.ACCESS_MEDIA_LOCATION:
          ^
          symbol:   variable ACCESS_MEDIA_LOCATION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:61: error: cannot find symbol
          case Manifest.permission.ACTIVITY_RECOGNITION:
          ^
          symbol:   variable ACTIVITY_RECOGNITION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:96: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
          ^
          symbol:   variable Q
          location: class VERSION_CODES
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:97: error: cannot find symbol
          if (hasPermissionInManifest(context, permissionNames, Manifest.permission.ACCESS_BACKGROUND_LOCATION))
          ^
          symbol:   variable ACCESS_BACKGROUND_LOCATION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:98: error: cannot find symbol
          permissionNames.add(Manifest.permission.ACCESS_BACKGROUND_LOCATION);
          ^
          symbol:   variable ACCESS_BACKGROUND_LOCATION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:136: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && hasPermissionInManifest(context, permissionNames, Manifest.permission.BIND_CALL_REDIRECTION_SERVICE))
          ^
          symbol:   variable Q
          location: class VERSION_CODES
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:136: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && hasPermissionInManifest(context, permissionNames, Manifest.permission.BIND_CALL_REDIRECTION_SERVICE))
          ^
          symbol:   variable BIND_CALL_REDIRECTION_SERVICE
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:137: error: cannot find symbol
          permissionNames.add(Manifest.permission.BIND_CALL_REDIRECTION_SERVICE);
          ^
          symbol:   variable BIND_CALL_REDIRECTION_SERVICE
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:183: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && hasPermissionInManifest(context, permissionNames, Manifest.permission.ACCESS_MEDIA_LOCATION))
          ^
          symbol:   variable Q
          location: class VERSION_CODES
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:183: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && hasPermissionInManifest(context, permissionNames, Manifest.permission.ACCESS_MEDIA_LOCATION))
          ^
          symbol:   variable ACCESS_MEDIA_LOCATION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:184: error: cannot find symbol
          permissionNames.add(Manifest.permission.ACCESS_MEDIA_LOCATION);
          ^
          symbol:   variable ACCESS_MEDIA_LOCATION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:188: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && hasPermissionInManifest(context, permissionNames, Manifest.permission.ACTIVITY_RECOGNITION))
          ^
          symbol:   variable Q
          location: class VERSION_CODES
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:188: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && hasPermissionInManifest(context, permissionNames, Manifest.permission.ACTIVITY_RECOGNITION))
          ^
          symbol:   variable ACTIVITY_RECOGNITION
          location: class permission
          /Volumes/demo/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:189: error: cannot find symbol
          permissionNames.add(Manifest.permission.ACTIVITY_RECOGNITION);
          ^
          symbol:   variable ACTIVITY_RECOGNITION
          location: class permission
          17 errors
          
          FAILURE: Build failed with an exception.
          
          * What went wrong:
          Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
          > Compilation failed; see the compiler error output for details.
          
          * Try:
          Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
          
          * Get more help at https://help.gradle.org
          
          BUILD FAILED in 19s
          Exception: Gradle task assembleDebug failed with exit code 1

**Comment by signshah** [comment]
After updating compileSdkVersion from 28 to 29, it stated working.
