### ISSUE TITLE
My app doesn't compile with higher versions than version 6.0.1+1

### ISSUE THREAD

**Issue by Blackoutseeker** [Baseflow/flutter-permission-handler#652]
## 🐛 Bug Report

I had the latest version of `permission_handler` (8.1.4 + 2) installed in my project (Android app), and it doesn't compile, with a lint issue in the package. So I downgraded the available versions to build my project correctly, and the version `6.0.1+1` worked for me.

In the `<root>/android` path, I runned `gradlew clean build`, and I faced this error message:

    > Task :permission_handler:lint FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':permission_handler:lint'.
    > Lint found errors in the project; aborting build.

      Fix the issues identified by lint, or add the following to your build script to proceed with errors:
      ...
      android {
          lintOptions {
              abortOnError false
          }
      }
      ...
      Errors found:

      C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-        8.1.4+2\android\src\main\java\com\baseflow\permissionhandler\ServiceManager.java:153: Error: Missing permissions required     by BluetoothAdapter.isEnabled: android.permission.BLUETOOTH [MissingPermission]
              return bluetoothAdapter.isEnabled();
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.1.4+2\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:58: Error: Call requires API level R (current min is 16): android.os.Environment#isExternalStorageManager [NewApi]
                  status = Environment.isExternalStorageManager()
                                       ~~~~~~~~~~~~~~~~~~~~~~~~

### Environment

OS:

    Windows 8.1 Pro

Flutter Doctor:

    [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [version 6.3.9600], locale pt-BR)
    [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    [√] Chrome - develop for the web
    [√] Android Studio (version 4.0)
    [√] IntelliJ IDEA Community Edition (version 2021.1)
    [√] VS Code (version 1.57.1)
    [√] Connected device (1 available)

    • No issues found!

pubspec.yaml:

    name: project
    description: app description.

    publish_to: "none"

    version: 1.0.0

    environment:
      sdk: ">=2.12.0 <3.0.0"

    dependencies:
      flutter:
        sdk: flutter

      qr_flutter: ^4.0.0
      qr_code_scanner: ^0.5.2
      screenshot: ^1.2.3
      image_gallery_saver: ^1.6.9
      permission_handler: 6.0.1+1
      url_launcher: ^6.0.9

    dev_dependencies:
      flutter_test:
        sdk: flutter

    flutter:
      uses-material-design: true

`<root>/android`/gradle.properties:

    org.gradle.jvmargs=-Xmx1536M
    android.useAndroidX=true
    android.enableJetifier=true

`<root>/android`/build.gradle:

    buildscript {
        ext.kotlin_version = '1.5.10'
        repositories {
            google()
            jcenter()
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:4.2.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        }
    }

    allprojects {
        repositories {
            google()
            jcenter()
        }
    }

    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
        project.evaluationDependsOn(':app')
    }

    task clean(type: Delete) {
        delete rootProject.buildDir
    }

`<root>/android/gradle/wrapper`/gradle-wrapper.properties:

    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip

`<root>/android/app`/build.gradle:

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }

    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }

    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }

    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }

    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

    android {
        lintOptions {
            abortOnError false
        }

        compileSdkVersion 30

        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }

        defaultConfig {
            applicationId "com.example.project"
            minSdkVersion 20
            targetSdkVersion 30
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
        }

        buildTypes {
            release {
                signingConfig signingConfigs.debug
            }
        }

    }

    flutter {
        source '../..'
    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    }

`<root>/android/app/src/main`/AndroidManifest.xml:

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.example.project">
      <uses-permission android:name="android.permission.INTERNET"/>
      <uses-permission android:name="android.permission.CAMERA"/>
      <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.BLUETOOTH"/>
      <application
            android:requestLegacyExternalStorage="true"
            android:label="project"
            android:icon="@mipmap/ic_launcher">
            <activity
                android:name=".MainActivity"
                android:launchMode="singleTop"
                android:theme="@style/LaunchTheme"
                android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                android:hardwareAccelerated="true"
                android:windowSoftInputMode="adjustResize">
                <!-- Specifies an Android theme to apply to this Activity as soon as
                    the Android process has started. This theme is visible to the user
                    while the Flutter UI initializes. After that, this theme continues
                    to determine the Window background behind the Flutter UI. -->
                <meta-data
                  android:name="io.flutter.embedding.android.NormalTheme"
                  android:resource="@style/NormalTheme"
                  />
                <!-- Displays an Android View that continues showing the launch screen
                    Drawable until Flutter paints its first frame, then this splash
                    screen fades out. A splash screen is useful to avoid any visual
                    gap between the end of Android's launch screen and the painting of
                    Flutter's first frame. -->
                <meta-data
                  android:name="io.flutter.embedding.android.SplashScreenDrawable"
                  android:resource="@drawable/launch_background"
                  />
                <intent-filter>
                    <action android:name="android.intent.action.MAIN"/>
                    <category android:name="android.intent.category.LAUNCHER"/>
                </intent-filter>
            </activity>
            <!-- Don't delete the meta-data below.
                This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
            <meta-data
                android:name="flutterEmbedding"
                android:value="2" />
        </application>
        <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
        </queries>
    </manifest>

### What I had already tried:

* Add Bluetooth permission on `AndroidManifest.xml`;
* Setting `abortOnError` to `false` in `android > lintOptions` on `<root>/android/app/build.gradle`;
* Create a new clean Flutter project, installing just `permission_handler: ^8.1.4+2`.

### Expected behavior

Compile my Android app correctly.

### Reproduction steps

Just create a new Flutter project and install `permission_handler` in its latest version.

**Comment by JDDV** [comment]
Hi @Blackoutseeker, thank you for the clear bug report with all the information.

The reason it worked on version `^6.0.1+1` is because of the permissions that gives the warnings as mentioned in this part

> C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-        8.1.4+2\android\src\main\java\com\baseflow\permissionhandler\ServiceManager.java:153: Error: Missing permissions required     by BluetoothAdapter.isEnabled: android.permission.BLUETOOTH [MissingPermission]
>           return bluetoothAdapter.isEnabled();
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.1.4+2\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:58: Error: Call requires API level R (current min is 16): android.os.Environment#isExternalStorageManager [NewApi]
>               status = Environment.isExternalStorageManager()
>                                    ~~~~~~~~~~~~~~~~~~~~~~~~

did not exist in that version of the `permission_handler`.

I created a new Flutter project (the standard counter app) and added the newest version of the `permission_handler` in the `pub spec.yaml`. For me it does work, and the built does not get aborted because of some warnings. I also don't use `lint`, so I'm pretty sure that is giving you the problems. 


> Setting abortOnError to false in android > lintOptions on <root>/android/app/build.gradle;

That does mean you did add the
```
lintOptions {
        abortOnError false
    }

```

in the `android {}` scope?

**Comment by Blackoutseeker** [comment]
Yes, like the `build.gradle` configuration shown above, I had already disabled the lint in the `android {}` scope.

`<root>/android/app`/build.gradle:

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }

    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }

    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }

    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }

    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

    android {
        lintOptions {
            abortOnError false
        }

        compileSdkVersion 30

        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }

        defaultConfig {
            applicationId "com.example.project"
            minSdkVersion 20
            targetSdkVersion 30
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
        }

        buildTypes {
            release {
                signingConfig signingConfigs.debug
            }
        }

    }

    flutter {
        source '../..'
    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    }

It looks like this configuration is being ignored by Gradle... But how?

I Googled about this possibility and tried this [solution](https://stackoverflow.com/questions/46435637/lintoptions-not-being-recognized-by-gradle) (which also didn't work).

Could you create a repository with the code you mentioned working?

**Comment by JuanxCursed** [comment]
Same issue here, I'm about 2 days trying to figure out how to fix it.
I already create a clean project just with permissions_handler, and doesn't build.
