### ISSUE TITLE
Build error with gradle 4.1.2

### ISSUE THREAD

**Issue by pawelpetruch** [Baseflow/flutter-permission-handler#689]
### Try to run a flutter app
```/Projects/_Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.2.0/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java:152: warning: [deprecation] getDefaultAdapter() in BluetoothAdapter has been deprecated
        final BluetoothAdapter bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
                                                                  ^
error: warnings found and -Werror specified

1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

It works fine with build gradle 4.0.2 but doesn't with 4.1.2

### flutter_permission_handler: ^7.0.0

**Version:** 1.x

**Platform:** 
- Android

**Comment by okocsis** [comment]
> Seems to do with manifest or something?
> 
> ![image](https://user-images.githubusercontent.com/16344370/136330784-08c63514-9c4b-4c94-a19c-c56422d3ab44.png)

same here
